package au.edu.unsw.soacourse.onboardingservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2017-03-25T20:42:20.292+11:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "OnboadrdingValidationServiceImplService", 
                  wsdlLocation = "http://localhost:8080/onboarding-validation-service/OnboadrdingValidationService?wsdl",
                  targetNamespace = "http://onboardingservice.soacourse.unsw.edu.au/") 
public class OnboadrdingValidationServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://onboardingservice.soacourse.unsw.edu.au/", "OnboadrdingValidationServiceImplService");
    public final static QName OnboadrdingValidationServiceImplPort = new QName("http://onboardingservice.soacourse.unsw.edu.au/", "OnboadrdingValidationServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/onboarding-validation-service/OnboadrdingValidationService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OnboadrdingValidationServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/onboarding-validation-service/OnboadrdingValidationService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OnboadrdingValidationServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OnboadrdingValidationServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OnboadrdingValidationServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OnboadrdingValidationServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OnboadrdingValidationServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OnboadrdingValidationServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns OnboadrdingValidationService
     */
    @WebEndpoint(name = "OnboadrdingValidationServiceImplPort")
    public OnboadrdingValidationService getOnboadrdingValidationServiceImplPort() {
        return super.getPort(OnboadrdingValidationServiceImplPort, OnboadrdingValidationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OnboadrdingValidationService
     */
    @WebEndpoint(name = "OnboadrdingValidationServiceImplPort")
    public OnboadrdingValidationService getOnboadrdingValidationServiceImplPort(WebServiceFeature... features) {
        return super.getPort(OnboadrdingValidationServiceImplPort, OnboadrdingValidationService.class, features);
    }

}
